res_jmp_no_fiter = {
    "question": "Sanitation",
    "data": [
        {
            "year": 2023,
            "history": False,
            "administration": "Malaita",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Rennell and Bellona",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Temotu",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Western",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Choiseul",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Guadalcanal",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 1,
                    "percent": 100.0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Honiara",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Isabel",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Makira and Ulawa",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Central",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
    ],
}


res_jmp_history_no_filter = {
    "question": "Sanitation",
    "data": [
        {
            "year": 2018,
            "history": True,
            "administration": "Malaita",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Rennell and Bellona",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Temotu",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Western",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Choiseul",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Guadalcanal",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 1,
                    "percent": 100.0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Honiara",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Isabel",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Makira and Ulawa",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
        {
            "year": 2018,
            "history": True,
            "administration": "Central",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                    "order": 1,
                },
                {
                    "option": "Limited",
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                    "order": 2,
                },
                {
                    "option": "No Service",
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                    "order": 3,
                },
            ],
        },
    ],
}


res_jmp_filtered = {
    "question": "Sanitation",
    "data": [
        {
            "year": 2023,
            "history": False,
            "administration": "Malaita",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Rennell and Bellona",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Temotu",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Western",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Choiseul",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Guadalcanal",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 1,
                    "percent": 100.0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Honiara",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Isabel",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Makira and Ulawa",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Central",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
    ],
}


res_jmp_filter_by_prov_sc_type = {
    "question": "Sanitation",
    "data": [
        {
            "year": 2023,
            "history": False,
            "administration": "Malaita",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Rennell and Bellona",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Temotu",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Western",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Choiseul",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Guadalcanal",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Honiara",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Isabel",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Makira and Ulawa",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
        {
            "year": 2023,
            "history": False,
            "administration": "Central",
            "score": 0,
            "child": [
                {
                    "option": "Basic",
                    "order": 1,
                    "count": 0,
                    "percent": 0,
                    "color": "#ab47bc",
                },
                {
                    "option": "Limited",
                    "order": 2,
                    "count": 0,
                    "percent": 0,
                    "color": "#fff176",
                },
                {
                    "option": "No Service",
                    "order": 3,
                    "count": 0,
                    "percent": 0,
                    "color": "#FEBC11",
                },
            ],
        },
    ],
}
